feat(ci): fixing publish/publish_tag stage #10

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -85,6 +85,15 @@ publish_tag:
     entrypoint: [ "" ]
   script:
     - "if [ ! -f $CI_REGISTRY_ENV ]; then echo \"Error: $CI_REGISTRY_ENV artifact is missing! Re-run the 'prepare' stage!\"; exit 1; fi"
+    - |
+      # Check if the designated TAG_VERSION(+suffix) tag already exists locally or on the remote
+      if git rev-parse ${TAG_VERSION} >/dev/null 2>&1 || git ls-remote --tags origin ${TAG_VERSION} | grep -q ${TAG_VERSION}; then
+        # If TAG_VERSION exists, delete the original tag that triggered this job
+        git tag -d $CI_COMMIT_TAG || true  # Delete the tag locally, continue if it doesn't exist locally
+        git push origin :refs/tags/$CI_COMMIT_TAG  # Delete the tag on the remote
+        echo "Error: Tag ${TAG_VERSION} already exists. The original tag $CI_COMMIT_TAG has been deleted."
+        exit 1
+      fi
     - git config user.name "$CI_USER"
     - git config user.email "$CI_USER_EMAIL"
     - git remote set-url origin "https://${CI_USER}:${CI_USER_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git"
