feat(ci): fixing publish/publish_tag stage

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,14 +1,38 @@
 variables:
   TEST_RESULTS_FILE: test-results.xml
 
-# Define rules for tags
-.rules_for_tags: &rules_for_tags
+# Define is_tag rule
+.is_tag: &is_tag
   if: '$CI_COMMIT_TAG'
   when: always
+
+# Define from_master rule
+.from_master: &from_master
+  if: '$CI_COMMIT_REF_NAME == "master"'
+  when: always
+
+# Define from_develop rule
+.from_develop: &from_develop
+  if: '$CI_COMMIT_REF_NAME == "develop"'
+  when: always
+
+# Define from_other rule
+.neither_from_master_nor_develop: &neither_from_master_nor_develop
+  if: '$CI_COMMIT_REF_NAME != "master" && $CI_COMMIT_REF_NAME != "develop"'
+  when: always
+
+# Define use_registry template
+.use_registry: &use_registry
+  stage: prepare
+  artifacts:
+    untracked: true
+    reports:
+      dotenv: $CI_REGISTRY_ENV
 
 # Define stages
 stages:
   - test
+  - prepare
   - publish
 
 # Run BATS tests (always)
@@ -26,26 +50,44 @@ bats_tests:
     reports:
       junit: $PWD/$TEST_RESULTS_FILE
 
+# Set TAG_VERSION according to tag being created from `master` branch
+tag_from_master:
+  <<: *use_registry
+  rules:
+    - <<: *from_master
+  script:
+    - echo "TAG_VERSION=$CI_COMMIT_TAG" > $CI_REGISTRY_ENV
+
+# Set TAG_VERSION according to tag being created from `develop` branch
+tag_from_develop:
+  <<: *use_registry
+  rules:
+    - <<: *from_develop
+  script:
+    - echo "TAG_VERSION=${CI_COMMIT_TAG}-SNAPSHOT" > $CI_REGISTRY_ENV
+
+# Set TAG_VERSION according to tag being created from any other branch
+tag_from_other:
+  <<: *use_registry
+  rules:
+    - <<: *neither_from_master_nor_develop
+  script:
+    - echo "TAG_VERSION=${CI_COMMIT_TAG}-BETA" > $CI_REGISTRY_ENV
+
 # Publish tag (only if tag is being created)
 publish_tag:
   stage: publish
   rules:
-    - <<: *rules_for_tags
+    - <<: *is_tag
   image:
     name: alpine/git:latest
     entrypoint: [ "" ]
   script:
+    - "if [ ! -f $CI_REGISTRY_ENV ]; then echo \"Error: $CI_REGISTRY_ENV artifact is missing! Re-run the 'prepare' stage!\"; exit 1; fi"
     - git config user.name "$CI_USER"
     - git config user.email "$CI_USER_EMAIL"
     - git remote set-url origin "https://${CI_USER}:${CI_USER_TOKEN}@gitlab.com/${CI_PROJECT_PATH}.git"
     - git checkout -b temp-branch
-    - if [ "$CI_COMMIT_REF_NAME" = "master" ]; then
-        TAG_VERSION="${CI_COMMIT_TAG}"
-      elfi [ "$CI_COMMIT_REF_NAME" = "develop" ]; then
-        TAG_VERSION="${CI_COMMIT_TAG}-SNAPSHOT"
-      else
-        TAG_VERSION="${CI_COMMIT_TAG}-BETA"
-      fi
     - for script in "scripts/*.sh"; do
         sed -i -E "s/(export SCRIPT_VERSION=\")([^\"]+)(\".*)/\1${TAG_VERSION}\3/" "$script"
       done
